name: responsive_magnoni
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.36
  confetti: ^0.7.0
  flutter_rating_bar: ^4.0.1
  provider: ^6.0.5
  intl: ^0.19.0
  image_picker: ^1.0.7
  path_provider: ^2.1.3
  cupertino_icons: ^1.0.6
  camera: ^0.10.6
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  table_calendar: ^3.1.2 # Added Calendar package

  # Supabase Package
  supabase_flutter: ^2.5.8

  # Firebase Packages
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  firebase_messaging: ^14.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/fiesta1.jpg
    - assets/images/bravo.jpg
    - assets/images/flexiones1.jpg
    - assets/images/desfile.jpg
    - assets/images/coolness.jpg
    - assets/images/suzy.jpg
    - assets/images/carl.jpg
    - assets/images/bunny.jpg
    - assets/images/heather.jpg
    - assets/images/song1.jpg
    - assets/images/song22.jpg
    - assets/images/song.jpg
    - assets/images/song5.jpg
    - assets/images/billete.png
    - assets/images/logo.jpg
    - assets/images/disco_ball.gif
    - assets/audio/mis_canciones/Johnny Bravo (opening español latino).mp3
    - assets/audio/mis_canciones/La canción de johnny Bravo  (mujer).mp3
    - assets/audio/mis_canciones/Johnny Bravo -  Hay un tipo guapo en mi casa.mp3
    - assets/audio/mis_canciones/3T - Why_ (Official Video) ft. Michael Jackson.mp3

  fonts:
    - family: WurmicsBravo
      fonts:
        - asset: assets/fonts/Wurmics_Bravo.ttf
